### ISSUE TITLE
How to use cucumber-electron to access a webpage for browser automation.

### ISSUE THREAD

**Issue by iowyncrox** [cucumber/cucumber-electron#24] opened 2018-03-10 16:27 UTC
How to use cucumber-electron to access a webpage for browser automation. For example a feature file like this:

```
Feature: Go to Google. Enter cucumber and check for a result
  Scenario: Running Google
    When I go to "www.google.com"
    And I enter the value "cucumber" in the input box with id "lst-ib"
    Then I click on the button "Google Search"
    Then I should see "Cucumber" as a link

```
In the When case on line 3: How to make use of the chrome browser inside electron to go to www.google.com

**Comment by aslakhellesoy** [comment] 2018-03-10 21:32
Cucumber-Electron is not a browser automation tool.

It's an environment that allows you to run the following things in the same process:

* Your own Node.js server process
* Your own DOM based UI (React, Vue, Angular, plain JavaScript)
* Cucumber.js

The purpose of this is to have *very fast tests*, because you can remove *all I/O* layers between these 3 parts.

Anything to add @joshski

**Comment by joshski** [comment] 2018-03-11 09:33
That’s right, cucumber-electron is not a browser automation tool.

So it is useful in the context of developing browser apps, particularly when the app includes client and server JavaScript. But it’s not very useful as a regression testing tool. I think the readme could clarify this point.

If you are determined, you _could_ use cucumber-electron to automate the scenario in question by appending an iframe to the document (which is implicitly in scope in step definitions) and setting its `src` to http://www.google.com and then manipulating the iframe after it loads. But cucumber-electron isn’t designed with regression testing in mind, so it will never make this easy.

Therefore I’m closing this issue.

**Closed by joshski** 2018-03-11 09:33 UTC

**Comment by felipemullen** [comment] 2019-09-26 17:18
@joshski I know this issue was closed a long time ago, I just wanted to mention the readme could indeed use a little more clarification at this point because there is a similarly-named package out there, called [electron-cucumber](https://github.com/mfcollins3/electron-cucumber).

I actually managed to get `cucumber-electron` working with puppeteer running automated tests but it was such a task to set up that I second-guessed whether I was doing the right thing and found this issue. Perhaps I'm not the only one who did so?
